[options]
; odoo-debian-bedrock instance config (staging etc.). Managed by 81-staging.sh.
admin_passwd = @ADMIN_PASSWD@
db_host = False
db_port = False
db_user = @DB_USER@
db_password = False
dbfilter = @DBFILTER@
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
list_db = True
http_port = @HTTP_PORT@
longpolling_port = @LONGPOLLING_PORT@
addons_path = @VENV_ADDONS@,/usr/lib/python3/dist-packages/odoo/addons
